# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Oswaldo Ferreira'
tagline:          'Tagline teste'
description:      'All about code.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Oswaldo Ferreira'
  url:            https://twitter.com/oswferreira

paginate: 10

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

analytics:
  provider: google
  google:
    tracking_id: 'UA-50742105-2'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
